/**
 * (C) 2025 Fraunhofer AISEC
 */

/**
 * @file bbs.h
 * @author Thomas Bellebaum
 * @author Sebastian Schmiedmayer
 * @author Martin Schanzenbach
 * @date 2 Jun 2025
 * @brief The main libbbs header file.
 */

#ifndef BBS_H
#define BBS_H

#include <stddef.h>
#include <stdint.h>
#include <stdarg.h>

/**
 * @brief Octet string length of secret key
 */
#define BBS_SK_LEN                     32

/**
 * @brief Octet string length of public key
 */
#define BBS_PK_LEN                     96

/**
 * @brief Octet string length of signature
 */
#define BBS_SIG_LEN                    80

/**
 * @brief Minimum octet string length of proof
 */
#define BBS_PROOF_BASE_LEN             272

/**
 * @brief Octet string length of UD element
 */
#define BBS_PROOF_UD_ELEM_LEN          32

/**
 * @brief Macro that calculates the octet string
 * length of proof with @p num_undisclosed number of undisclosed
 * messages.
 */
#define BBS_PROOF_LEN(num_undisclosed) (BBS_PROOF_BASE_LEN + (num_undisclosed) * BBS_PROOF_UD_ELEM_LEN \
					)

/**
 * @brief return value on success
 */
#define BBS_OK    0

/**
 * @brief return value on error
 */
#define BBS_ERROR 1

/**
 * @brief BBS secret key
 *
 * The secret key is an octet string of
 * length #BBS_SK_LEN.
 */
typedef uint8_t  bbs_secret_key[BBS_SK_LEN];

/**
 * @brief BBS public key
 *
 * The public key is an octet string of
 * length #BBS_PK_LEN.
 */
typedef uint8_t  bbs_public_key[BBS_PK_LEN];

/**
 * @brief BBS signature
 *
 * The BBS signature is an octet string of
 * length #BBS_SIG_LEN.
 */
typedef uint8_t  bbs_signature[BBS_SIG_LEN];

/**
 * @brief BBS cipher suite
 *
 * The cipher suite. Is one of
 * #bbs_sha256_cipher_suite or #bbs_shake256_cipher_suite
 */
typedef struct bbs_cipher_suite bbs_cipher_suite_t;

// Key Generation

/**
 * Generate a public/private key pair.
 * This is a convienience function for #bbs_keygen
 * in which the @p key_dst and @p key_info parameters
 * are the empty string.
 *
 * @param cipher_suite the cipher suite to use. See #bbs_cipher_suite_t.
 * @param sk where to store the secret key
 * @param pk where to store the public key
 * @return 0 on success.
 */
int bbs_keygen_full (
	const bbs_cipher_suite_t *cipher_suite,
	bbs_secret_key            sk,
	bbs_public_key            pk
	);


/**
 * Generate a public/private key pair
 *
 * For security, key_material MUST be random and infeasible to guess,
 * e.g. generated by a trusted source of randomness and with enough entropy.
 * See [RFC4086] for suggestions on generating randomness.
 * @p key_material MUST be at least 32 bytes long, but it MAY be longer.
 *
 * @param cipher_suite the cipher suite to use. See #bbs_cipher_suite_t.
 * @param sk where to store the secret key
 * @param key_material a secret octet string. See requirements above.
 * @param key_material_len the length of @p key_material
 * @param key_info used to derive distinct keys from the same key material. (may be NULL)
 * @param key_info_len the length of @p key_info
 * @param key_dst an octet string representing the domain separation tag.
 *                May be NULL in which case it to the octet string
                  @p ciphersuite_id || "KEYGEN_DST_".
 * @param key_dst_len the length of @p key_dst
 * @return 0 on success.
 */
int bbs_keygen (
	const bbs_cipher_suite_t *cipher_suite,
	bbs_secret_key            sk,
	const uint8_t            *key_material,
	size_t                    key_material_len,
	const uint8_t            *key_info,
	size_t                    key_info_len,
	const uint8_t            *key_dst,
	size_t                    key_dst_len
	);

/**
 * Generate public key from secret key.
 * Internally generates randomness for @p key_material and calls
 * #bbs_keygen with default parameters.
 *
 * @param cipher_suite the cipher suite to use. See #bbs_cipher_suite_t.
 * @param sk secret key.
 * @param pk public key.
 * @return #BBS_OK on success.
 */
int bbs_sk_to_pk (
	const bbs_cipher_suite_t *cipher_suite,
	const bbs_secret_key      sk,
	bbs_public_key            pk
	);

/**
 * @brief Create a signature.
 *
 * The @p num_messages is followed by
 * this amount of varargs that consist of
 * a tuple of uint8_t* pointers to octet strings
 * followed by a uint32_t length indicator.
 *
 * @param cipher_suite the cipher suite to use. See #bbs_cipher_suite_t.
 * @param sk secret key.
 * @param pk public key.
 * @param signature where to store the signature.
 * @param header an octet string containing context and application
                 specific information. If not supplied, it defaults
                 to the empty octet string ("").
 * @param header_len the length of the message header.
 * @param num_messages the number of messages as octet strings followed in varargs.
 * @return #BBS_OK on success.
 */
int bbs_sign_v (
	const bbs_cipher_suite_t *cipher_suite,
	const bbs_secret_key      sk,
	const bbs_public_key      pk,
	bbs_signature             signature,
	const uint8_t            *header,
	size_t                    header_len,
	uint64_t                  num_messages,
	...
	);

/**
 * @brief Create a signature.
 *
 * The @p num_messages is followed by
 * arrays of the same length that contain
 * the messages and their lengths.
 *
 * @param cipher_suite the cipher suite to use. See #bbs_cipher_suite_t.
 * @param sk secret key.
 * @param pk public key.
 * @param signature where to store the signature.
 * @param header an octet string containing context and application
                 specific information. If not supplied, it defaults
                 to the empty octet string ("").
 * @param header_len the length of the message header.
 * @param num_messages the number of messages as octet strings followed in varargs.
 * @param messages the messages.
 * @param messages_lens the message lengths.
 * @return #BBS_OK on success.
 */
int bbs_sign (
	const bbs_cipher_suite_t *cipher_suite,
	const bbs_secret_key      sk,
	const bbs_public_key      pk,
	bbs_signature             signature,
	const uint8_t            *header,
	size_t                    header_len,
	uint64_t                  num_messages,
	const uint8_t *const     *messages,
	const size_t             *messages_lens
	);

/**
 * @brief Verify a signature.
 *
 * The @p num_messages is followed by
 * this amount of varargs that consist of
 * a tuple of uint8_t* pointers to octet strings
 * followed by a uint32_t length indicator.
 *
 * @param cipher_suite the cipher suite to use. See #bbs_cipher_suite_t.
 * @param pk public key.
 * @param signature the signature to verify.
 * @param header an octet string containing context and application
                 specific information. If not supplied, it defaults
                 to the empty octet string ("").
 * @param header_len the length of the message header.
 * @param num_messages the number of messages followed by in varargs.
 * @return #BBS_OK on success.
 */
int bbs_verify_v (
	const bbs_cipher_suite_t *cipher_suite,
	const bbs_public_key      pk,
	const bbs_signature       signature,
	const uint8_t            *header,
	size_t                    header_len,
	uint64_t                  num_messages,
	...
	);


/**
 * @brief Verify a signature.
 *
 * The @p num_messages is followed by
 * this amount of varargs that consist of
 * a tuple of uint8_t* pointers to octet strings
 * followed by a uint32_t length indicator.
 *
 * @param cipher_suite the cipher suite to use. See #bbs_cipher_suite_t.
 * @param pk public key.
 * @param signature the signature to verify.
 * @param header an octet string containing context and application
                 specific information. If not supplied, it defaults
                 to the empty octet string ("").
 * @param header_len the length of the message header.
 * @param num_messages the number of messages followed by in varargs.
 * @param messages the messages.
 * @param messages_lens the message lengths.
 * @return #BBS_OK on success.
 */
int bbs_verify (
	const bbs_cipher_suite_t *cipher_suite,
	const bbs_public_key      pk,
	const bbs_signature       signature,
	const uint8_t            *header,
	size_t                    header_len,
	uint64_t                  num_messages,
	const uint8_t *const     *messages,
	const size_t             *messages_lens
	);

/**
 * @brief Create a proof over a signature.
 *
 * The @p num_messages is followed by
 * this amount of varargs that consist of
 * a tuple of uint8_t* pointers to octet strings
 * followed by a uint32_t length indicator.
 *
 * @param cipher_suite the cipher suite to use. See #bbs_cipher_suite_t.
 * @param pk public key.
 * @param signature the signature to use.
 * @param proof pointer to the proof.
 *              Must be allocated by caller as octet string
 *              with size BBS_PROOF_LEN(N) where
 *              N = (@p num_messages - @p disclosed_indexes_len).
 * @param header an octet string containing context and application
                 specific information. If not supplied, it defaults
                 to the empty octet string ("").
 * @param header_len the length of the message header.
 * @param presentation_header an octet string containing the presentation header.
 *                            If not supplied, it defaults to the empty octet
                              string ("").
 * @param presentation_header_len the length of the proof presentation header.
 * @param disclosed_indexes a vector of unsigned integers in ascending
                            order. Indexes of disclosed messages. If
                            not supplied, it defaults to the empty
                            array ("()").
 * @param disclosed_indexes_len the length of @p disclosed_indexes array.
 * @param num_messages the number of messages followed by in varargs.
 * @return #BBS_OK on success.
 */
int bbs_proof_gen_v (
	const bbs_cipher_suite_t *cipher_suite,
	const bbs_public_key      pk,
	const bbs_signature       signature,
	uint8_t                  *proof,
	const uint8_t            *header,
	size_t                    header_len,
	const uint8_t            *presentation_header,
	size_t                    presentation_header_len,
	const uint64_t           *disclosed_indexes,
	size_t                    disclosed_indexes_len,
	uint64_t                  num_messages,
	...
	);


/**
 * @brief Create a proof over a signature.
 *
 * The @p num_messages is followed by
 * this amount of varargs that consist of
 * a tuple of uint8_t* pointers to octet strings
 * followed by a uint32_t length indicator.
 *
 * @param cipher_suite the cipher suite to use. See #bbs_cipher_suite_t.
 * @param pk public key.
 * @param signature the signature to use.
 * @param proof pointer to the proof.
 *              Must be allocated by caller as octet string
 *              with size BBS_PROOF_LEN(N) where
 *              N = (@p num_messages - @p disclosed_indexes_len).
 * @param header an octet string containing context and application
                 specific information. If not supplied, it defaults
                 to the empty octet string ("").
 * @param header_len the length of the message header.
 * @param presentation_header an octet string containing the presentation header.
 *                            If not supplied, it defaults to the empty octet
                              string ("").
 * @param presentation_header_len the length of the proof presentation header.
 * @param disclosed_indexes a vector of unsigned integers in ascending
                            order. Indexes of disclosed messages. If
                            not supplied, it defaults to the empty
                            array ("()").
 * @param disclosed_indexes_len the length of @p disclosed_indexes array.
 * @param num_messages the number of messages followed by in varargs.
 * @param messages the messages.
 * @param messages_lens the message lengths.
 * @return #BBS_OK on success.
 */
int bbs_proof_gen (
	const bbs_cipher_suite_t *cipher_suite,
	const bbs_public_key      pk,
	const bbs_signature       signature,
	uint8_t                  *proof,
	const uint8_t            *header,
	size_t                    header_len,
	const uint8_t            *presentation_header,
	size_t                    presentation_header_len,
	const uint64_t           *disclosed_indexes,
	size_t                    disclosed_indexes_len,
	uint64_t                  num_messages,
	const uint8_t *const     *messages,
	const size_t             *messages_lens
	);

/**
 * @brief Verify a proof over a signature.
 *
 * The @p num_messages is followed by
 * this amount of varargs that consist of
 * a tuple of uint8_t* pointers to octet strings
 * followed by a uint32_t length indicator.
 *
 * @param cipher_suite the cipher suite to use. See #bbs_cipher_suite_t.
 * @param pk public key.
 * @param proof an octet string of the form outputted by #bbs_proof_gen.
 * @param proof_len length of @p proof.
 * @param header an octet string containing context and application
                 specific information. If not supplied, it defaults
                 to the empty octet string ("").
 * @param header_len the length of the message header.
 * @param presentation_header an octet string containing the presentation header.
 *                            If not supplied, it defaults to the empty octet
                              string ("").
 * @param presentation_header_len the length of the proof presentation header.
 * @param disclosed_indexes a vector of unsigned integers in ascending
                            order. Indexes of disclosed messages. If
                            not supplied, it defaults to the empty
                            array ("()").
  * @param disclosed_indexes_len the length of @p disclosed_indexes array.
 * @param num_messages the number of messages followed by in varargs.
 * @return #BBS_OK on success.
 */
int bbs_proof_verify_v (
	const bbs_cipher_suite_t *cipher_suite,
	const bbs_public_key      pk,
	const uint8_t            *proof,
	size_t                    proof_len,
	const uint8_t            *header,
	size_t                    header_len,
	const uint8_t            *presentation_header,
	size_t                    presentation_header_len,
	const uint64_t           *disclosed_indexes,
	size_t                    disclosed_indexes_len,
	uint64_t                  num_messages,
	...
	);

/**
 * @brief Verify a proof over a signature.
 *
 * The @p num_messages is followed by
 * this amount of varargs that consist of
 * a tuple of uint8_t* pointers to octet strings
 * followed by a uint32_t length indicator.
 *
 * @param cipher_suite the cipher suite to use. See #bbs_cipher_suite_t.
 * @param pk public key.
 * @param proof an octet string of the form outputted by #bbs_proof_gen.
 * @param proof_len length of @p proof.
 * @param header an octet string containing context and application
                 specific information. If not supplied, it defaults
                 to the empty octet string ("").
 * @param header_len the length of the message header.
 * @param presentation_header an octet string containing the presentation header.
 *                            If not supplied, it defaults to the empty octet
                              string ("").
 * @param presentation_header_len the length of the proof presentation header.
 * @param disclosed_indexes a vector of unsigned integers in ascending
                            order. Indexes of disclosed messages. If
                            not supplied, it defaults to the empty
                            array ("()").
 * @param disclosed_indexes_len the length of @p disclosed_indexes array.
 * @param num_messages the number of messages followed by in varargs.
 * @param messages the messages.
 * @param messages_lens the message lengths.
 * @return #BBS_OK on success.
 */
int bbs_proof_verify (
	const bbs_cipher_suite_t *cipher_suite,
	const bbs_public_key      pk,
	const uint8_t            *proof,
	size_t                    proof_len,
	const uint8_t            *header,
	size_t                    header_len,
	const uint8_t            *presentation_header,
	size_t                    presentation_header_len,
	const uint64_t           *disclosed_indexes,
	size_t                    disclosed_indexes_len,
	uint64_t                  num_messages,
	const uint8_t *const     *messages,
	const size_t             *messages_lens
	);

/**
 * The SHA256 cipher suite
 *
 * @see #bbs_cipher_suite_t
 */
extern const bbs_cipher_suite_t *const bbs_sha256_cipher_suite;

/**
 * Helper for SHA256 suite
 * @see #bbs_keygen_full
 */
#define bbs_sha256_keygen_full(...)  bbs_keygen_full(bbs_sha256_cipher_suite,__VA_ARGS__)

/**
 * Helper for SHA256 suite
 * @see #bbs_keygen
 */
#define bbs_sha256_keygen(...)       bbs_keygen(bbs_sha256_cipher_suite,__VA_ARGS__)

/**
 * Helper for SHA256 suite
 * @see #bbs_sk_to_pk
 */
#define bbs_sha256_sk_to_pk(...)     bbs_sk_to_pk(bbs_sha256_cipher_suite,__VA_ARGS__)

/**
 * Helper for SHA256 suite
 * @see #bbs_sign
 */
#define bbs_sha256_sign(...)         bbs_sign(bbs_sha256_cipher_suite,__VA_ARGS__)

/**
 * Helper for SHA256 suite
 * @see #bbs_verify
 */
#define bbs_sha256_verify(...)       bbs_verify(bbs_sha256_cipher_suite,__VA_ARGS__)

/**
 * Helper for SHA256 suite
 * @see #bbs_proof_gen
 */
#define bbs_sha256_proof_gen(...)    bbs_proof_gen(bbs_sha256_cipher_suite,__VA_ARGS__)

/**
 * Helper for SHA256 suite
 * @see #bbs_proof_verify
 */
#define bbs_sha256_proof_verify(...) bbs_proof_verify(bbs_sha256_cipher_suite,__VA_ARGS__)

/**
 * The SHAKE256 cipher suite
 *
 * @see #bbs_cipher_suite_t
 */
extern const bbs_cipher_suite_t *const bbs_shake256_cipher_suite;

/**
 * Helper for SHAKE256 suite
 * @see #bbs_keygen_full
 */

#define bbs_shake256_keygen_full(...)  bbs_keygen_full(bbs_shake256_cipher_suite,__VA_ARGS__)
/**
 * Helper for SHAKE256 suite
 * @see #bbs_keygen
 */
#define bbs_shake256_keygen(...)       bbs_keygen(bbs_shake256_cipher_suite,__VA_ARGS__)

/**
 * Helper for SHAKE256 suite
 * @see #bbs_sk_to_pk
 */
#define bbs_shake256_sk_to_pk(...)     bbs_sk_to_pk(bbs_shake256_cipher_suite,__VA_ARGS__)

/**
 * Helper for SHAKE256 suite
 * @see #bbs_sign
 */
#define bbs_shake256_sign(...)         bbs_sign(bbs_shake256_cipher_suite,__VA_ARGS__)

/**
 * Helper for SHAKE256 suite
 * @see #bbs_verify
 */
#define bbs_shake256_verify(...)       bbs_verify(bbs_shake256_cipher_suite,__VA_ARGS__)

/**
 * Helper for SHAKE256 suite
 * @see #bbs_proof_gen
 */
#define bbs_shake256_proof_gen(...)    bbs_proof_gen(bbs_shake256_cipher_suite,__VA_ARGS__)

/**
 * Helper for SHAKE256 suite
 * @see #bbs_proof_verify
 */
#define bbs_shake256_proof_verify(...) bbs_proof_verify(bbs_shake256_cipher_suite,__VA_ARGS__)

#endif
